-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.env("XCURSOR_SIZE", 24)

hl.env("_JAVA_AWT_WM_NONREPARENTING", 1)

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("XDG_SESSION_TYPE", "wayland")

-- env = GBM_BACKEND,nvidia-drm

-- env = __GLX_VENDOR_LIBRARY_NAME,nvidia

hl.env("WLR_NO_HARDWARE_CURSORS", 1)

--env = WLR_DRM_DEVICES,/dev/dri/card0

--env = WLR_DRM_DEVICES,/dev/dri/card0:/dev/dri/card1

hl.env("MOZ_ENABLE_WAYLAND", 1)

--env = MOZ_DBUS_REMOTE,1

hl.env("HYPRSHOT_DIR", os.getenv("HOME") .. "/Pictures")

hl.env("GDK_BACKEND", "wayland,x11")

--env =  QT_QPA_PLATFORM,wayland

-- env =  QT_QPA_PLATFORM,wayland;xcb

-- env =  QT_QPA_PLATFORMTHEME,qt6ct

hl.env("QT_QPA_PLATFORMTHEME", "hyprqt6engine")

-- env = QT_STYLE_OVERRIDE,kvantum

hl.env("SDL_VIDEODRIVER", "wayland")

hl.env("CLUTTER_BACKEND", "wayland")

--env = WLR_DRM_NO_ATOMIC,1

hl.env("XDG_MENU_PREFIX", "plasma-")
