-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

--

--autogenerated = 1 # remove this line to remove the warning

-- See https://wiki.hyprland.org/Configuring/Monitors/

--monitor=,preferred,auto,1

hl.monitor({
  output   = "eDP-1",
  mode     = "preferred",
  position = "0x0",
  scale    = 1,
})

--monitor=HDMI-A-1,preferred,auto,1,mirror,eDP-1

-- monitor=eDP-1,preferred,0x0,1,bitdepth,10

-- monitor=HDMI-A-1,preferred,1920x0,auto

-- monitor=HDMI-A-1,preferred,auto,auto

-- monitor=HDMI-A-1,2560x1440@144,1920x-360,1

hl.monitor({
  output   = "DP-1",
  mode     = "2560x1440@180",
  position = "1920x-360",
  scale    = 1,
})

-- monitor=DP-1,2560x1440@180,1920x-360,1.333333

-- monitor=DP-1,2560x1440@180,1920x-360,1,bitdepth,10,cm,hdr,sdrsaturation,1.0

-- monitor=DP-1,2560x1440@180,1920x-360,1,bitdepth,10,cm,hdredid,sdrbrightness,1.5,sdrsaturation,1.0

-- monitor=HDMI-A-1,preferred,auto,auto,bitdepth,10

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

-- Execute your favorite apps at launch


-- Source a file (multi-file configs)

-- source = ~/.config/hypr/myColors.conf

-- source = ~/.config/hypr/startup.conf -> requires manual conversion
local startup = require("startup")
-- TODO: convert ~/.config/hypr/startup.conf to .lua and use require()

-- source = ~/.config/hypr/workspaces.conf -> requires manual conversion
local workspaces = require("workspaces")
-- TODO: convert ~/.config/hypr/workspaces.conf to .lua and use require()

-- source = ~/.config/hypr/window-rules.conf -> requires manual conversion
local window_rules = require("window-rules")
-- TODO: convert ~/.config/hypr/window-rules.conf to .lua and use require()

-- source = ~/.config/hypr/shortcuts.conf -> requires manual conversion
local shortcuts = require("shortcuts")
-- TODO: convert ~/.config/hypr/shortcuts.conf to .lua and use require()

-- Some default env vars.

hl.env("XCURSOR_SIZE", 24)

-- source = ~/.config/hypr/env.conf -> requires manual conversion
local env = require("env")
-- TODO: convert ~/.config/hypr/env.conf to .lua and use require()

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.config({
  input = {
    kb_layout = "us",
    kb_variant = "",
    kb_model = "",
    kb_options = "",
    kb_rules = "",
    follow_mouse = 1,
    touchpad = {
      --natural_scroll = no
      natural_scroll = true,
    },
    sensitivity = 0,
    -- -1.0 - 1.0, 0 means no modification.
    numlock_by_default = true,
  },
})

-- device:elan0521:01-04f3:31b1-touchpad {

--     accel_profile = adaptive

-- }

hl.config({
  general = {
    -- See https://wiki.hyprland.org/Configuring/Variables/ for more
    gaps_in = 10,
    gaps_out = 20,
    border_size = 3,
    --col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    -- col.active_border = rgba(5657f5ff)
    --col.active_border = rgba(ff8f36ee) rgba(ff368fee) 45deg
    -- col.active_border = rgba(5657f5ff)
    -- col.active_border = "rgba(F06292ff)",
    --col.inactive_border = rgba(595959aa)
    -- col.inactive_border = rgba(32343dcc)
    --col.inactive_border = rgba(31313acc)
    -- col.inactive_border = "rgba(1d212fcc)",
    col = {
      active_border = 0xffF06292,
      inactive_border = 0xcc1d212f,
    },
    layout = "dwindle",
  },
})

hl.config({
  decoration = {
    -- See https://wiki.hyprland.org/Configuring/Variables/ for more
    rounding = 20,
    blur = {
      enabled = true,
      size = 15,
      passes = 2,
      noise = 0.2,
      contrast = 1,
      new_optimizations = true,
      popups = true,
    },
    shadow = {
      enabled = true,
      range = 9,
      render_power = 3,
      color = "rgba(31313a11)",
    },
  },
})

hl.config({
  animations = {
    enabled = true,
    -- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
  },
})

hl.config({
  dwindle = {
    -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    -- pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true,
    -- you probably want this
    force_split = 2,
  },
})

hl.config({
  master = {
    -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    -- new_is_master = true
  },
})

hl.config({
  gestures = {
    -- See https://wiki.hyprland.org/Configuring/Variables/ for more
    -- workspace_swipe = off
  },
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#executing for more

-- device:epic mouse V1 {

--     sensitivity = -0.5

-- }

-- Example windowrule v1

-- windowrule = float, ^(kitty)$

-- Example windowrule v2

-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

hl.config({
  misc = {
    disable_hyprland_logo = true,
    disable_splash_rendering = true,
    middle_click_paste = false,
  },
})

hl.config({
  cursor = {
    no_hardware_cursors = true,
  },
})

-- experimental {

--   xx_color_management_v4 = true

-- }

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more
