-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local mainMod = "SUPER"

local TERM = "kitty"

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1, follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2, follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3, follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4, follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5, follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6, follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7, follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8, follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9, follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10, follow = false }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = -1 }))

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "+1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })




hl.bind(mainMod .. " + " .. "W", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "S", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "T", hl.dsp.window.pseudo())

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "M", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "RETURN", hl.dsp.exec_cmd(os.getenv("TERMINAL")))


hl.bind(mainMod .. " + " .. "SPACE", hl.dsp.exec_cmd("rofi -show combi"))

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("dolphin"))

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd(os.getenv("TERMINAL") .. " -e btm"))

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + " .. "TAB", hl.dsp.focus({ last = true }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.move({ direction = "l" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.move({ direction = "r" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.move({ direction = "u" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.move({ direction = "d" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.window.move({ direction = "l" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.window.move({ direction = "r" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.window.move({ direction = "u" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "J", hl.dsp.window.move({ direction = "d" }))

hl.bind(mainMod .. " + " .. "code:34", hl.dsp.focus({ workspace = -1 }))

hl.bind(mainMod .. " + " .. "code:35", hl.dsp.focus({ workspace = "+1" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:34", hl.dsp.window.move({ workspace = -1, follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:35", hl.dsp.window.move({ workspace = "+1", follow = false }))

hl.bind(mainMod .. " + " .. "code:59", hl.dsp.focus({ monitor = -1 }))

hl.bind(mainMod .. " + " .. "code:60", hl.dsp.focus({ monitor = "+1" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:59", hl.dsp.focus({ monitor = "left" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:60", hl.dsp.focus({ monitor = "right" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:59", hl.dsp.window.move({ monitor = -1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:60", hl.dsp.window.move({ monitor = "+1" }))

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("lightctl up"))

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("lightctl down"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +5%"))

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -5%"))

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"))

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))

hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"))

hl.bind("XF86Calculator", hl.dsp.exec_cmd("qalculate-qt"))


hl.bind("PRINT", hl.plugin.hyprcapture.open)

-- hl.bind("SUPER + SHIFT + w", function()
--   hl.plugin.hyprcapture.open("window")
-- end)

hl.bind("SHIFT + PRINT", function()
  hl.plugin.hyprcapture.open("fullscreen")
end)


hl.bind("CTRL + ALT" .. " + " .. "Delete", hl.dsp.exec_cmd("wlogout"))

hl.bind("CTRL + ALT" .. " + " .. "l", hl.dsp.exec_cmd("gtklock --follow-focus"))

-- bind = CTRL ALT,l, exec, hyprlock
