-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- exec-once = /usr/lib/polkit-kde-authentication-agent-1


-- exec-once = waybar

-- exec-once = /usr/bin/ags



-- exec-once = /usr/bin/agsv1 --config $HOME/.config/agsv1/config.js

-- exec-once = /usr/bin/ags --bus-name bar --config $HOME/.config/ags/bar/config.js

-- exec-once = /usr/bin/ags --bus-name osd --config $HOME/.config/ags/osd/config.js

-- exec-once = /usr/bin/ags --bus-name notifications --config $HOME/.config/ags/notification-popups/config.js

-- exec-once = /usr/bin/dunst


-- exec-once = blueman-applet

-- exec-once = swayidle -w timeout 300 'gtklock -d -i'

-- exec-once = swayidle -w timeout 300 hyprlock


-- exec-once = handle_monitor_connect.sh


-- exec-once = wl-paste --primary --watch wl-copy --primary --clear

-- exec-once = avizo-service

-- Autostart
hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("playerctld daemon")
  hl.exec_cmd("/usr/bin/ags run --gtk 3 > " .. os.getenv("HOME") .. "/ags.log")
  hl.exec_cmd("nm-applet --indicator")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("wl-clip-persist --clipboard regular")
  hl.exec_cmd("hyprpaper")
end)
