-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.window_rule({
  name  = "match_class___org_kd",
  match = {
    class = "float true",
  },
  -- TODO: review rule: "match:class ^(org.kde.polkit-kde-authentication-agent-1)$"
})

hl.window_rule({
  name  = "match_class___proton",
  match = {
    class = "float true",
  },
  -- TODO: review rule: "match:class ^(protonvpn)$"
})

hl.window_rule({
  name  = "match_class___pavuco",
  match = {
    class = "float true",
  },
  -- TODO: review rule: "match:class ^(pavucontrol)$"
})

hl.window_rule({
  name  = "match_class___zoom__",
  match = {
    class = "float true",
  },
  -- TODO: review rule: "match:class ^(zoom)$"
})

hl.window_rule({
  name  = "match_class_zenity",
  match = {
    class = "float true",
  },
  -- TODO: review rule: "match:class zenity"
})

hl.window_rule({
  name  = "match_class_blueman-",
  match = {
    class = "float true",
  },
  -- TODO: review rule: "match:class blueman-manager"
})

hl.window_rule({
  name  = "match_class___wofi__",
  match = {
    class = "no_anim true",
  },
  -- TODO: review rule: "match:class ^(wofi)$"
})

hl.window_rule({
  name  = "match_class___micros",
  match = {
    title = "title ^(Microsoft Teams Notification)$",
  },
  -- TODO: review rule: "match:class ^(Microsoft Teams- Preview)$"
})

-- hl.window_rule({
--   name  = "match_title_____",
--   match = {
--     match = "class ^()$",
--   },
--   -- TODO: review rule: "match:title ^()$"
-- })

hl.window_rule({
  name  = "match_class___xdg-de",
  match = {
    class = "no_blur true",
  },
  -- TODO: review rule: "match:class ^(Xdg-desktop-portal-gtk)$"
})

hl.window_rule({
  name  = "match_class___xdg-de",
  match = {
    class = "border_size 0",
  },
  -- TODO: review rule: "match:class ^(Xdg-desktop-portal-gtk)$"
})

hl.window_rule({
  name  = "match_class___xdg-de",
  match = {
    class = "no_shadow true",
  },
  -- TODO: review rule: "match:class ^(Xdg-desktop-portal-gtk)$"
})

-- no_anim isn't necessary but animations with these rules might look bad. use at your own discretion.

hl.window_rule({
  name    = "match_class___flames",
  match   = {
    class = "flames",
  },
  no_anim = true,
  -- TODO: review rule: "match:class ^(flameshot)$"
})

hl.window_rule({
  name  = "match_class___flames",
  match = {
    class = "flames",
  },
  float = true,
})


hl.window_rule({
  name  = "match_class___flames",
  match = {
    class = "flames",
  },
  pin   = true,
})



hl.window_rule({
  name    = "match_class___flames",
  match   = {
    class = "flames",
  },
  monitor = 1
})


hl.window_rule({
  name  = "match_class___satty",
  match = {
    class = "com.gabm.satty",
  },
  float = true,
})


-- layerrule=match:namespace gtk-layer-shell, blur true

hl.layer_rule({
  match = {
    namespace = "rofi",
  },
  blur = true,
})

-- layerrule=blur,rofi

-- layerrule=blur,notifications

-- layerrule=blur,calendarmenu

-- layerrule=blur,audiomenu

-- layerrule=blur,sessionmenu

-- layerrule=blur,osd

-- layerrule=blur,settings-0

-- layerrule=blur,settings-1

-- layerrule=blur,gtk-layer-shell

-- layerrule=blur,bar

hl.layer_rule({
  match = {
    namespace = "gtk-layer-shell"
  },
  ignore_alpha = 0.03,
})

hl.layer_rule({
  match = {
    namespace = "rofi",
  },
  ignore_alpha = 0.03,
})

-- layerrule=ignorealpha[0.97],rofi

-- layerrule=ignorealpha[0.97],notifications

-- layerrule=ignorealpha[0.97],calendarmenu

-- layerrule=ignorealpha[0.97],audiomenu

-- layerrule=ignorealpha[0.97],sessionmenu

-- layerrule=ignorealpha[0.97],osd

-- layerrule=ignorealpha[0.97],settings-0

-- layerrule=ignorealpha[0.97],settings-1

-- layerrule=ignorealpha[0.97],gtk-layer-shell

-- layerrule=ignorealpha[0.97],bar
