-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--workspace = 1, monitor:eDP-1

--workspace = 2, monitor:eDP-1

--workspace = 3, monitor:eDP-1

--workspace = 4, monitor:eDP-1

--workspace = 5, monitor:eDP-1

--workspace = 6, monitor:eDP-1

--workspace = 7, monitor:eDP-1

--workspace = 8, monitor:eDP-1

--workspace = 9, monitor:eDP-1

--workspace = 10, monitor:eDP-1

-- workspace = 1, monitor:HDMI-A-1

-- workspace = 2, monitor:HDMI-A-1

-- workspace = 3, monitor:HDMI-A-1

-- workspace = 4, monitor:HDMI-A-1

-- workspace = 5, monitor:HDMI-A-1

-- workspace = 6, monitor:HDMI-A-1

-- workspace = 7, monitor:HDMI-A-1

-- workspace = 8, monitor:HDMI-A-1

-- workspace = 9, monitor:HDMI-A-1

-- workspace = 10, monitor:eDP-1

hl.workspace_rule({
    workspace = 1,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 2,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 3,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 4,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 5,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 6,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 7,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 8,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 9,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 10,
    monitor = "eDP-1",
})
