# Don't print a new line at the start of the prompt
# add_newline = false

[cmd_duration]
show_notifications = true

[git_branch]
symbol = " "

[hostname]
#ssh_only = false

[line_break]
#disabled = true

[status]
disabled = false

[time]
use_12hr = true
#disabled = false

[username]
#show_always = true
