#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#pkill polybar
#~/.config/polybar/launch.sh

pkill picom
#picom --experimental-backends &
picom &

#bspc monitor -d I II III IV V VI VII VIII IX X 
bspc monitor -d     爵   調  
bspc config merge_overlapping_monitors true

bspc config border_width         3
bspc config window_gap          15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 28

bspc config focused_border_color "#5294e2"
bspc config normal_border_color "#32343d"


#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc rule -a Vivaldi-stable desktop=
bspc rule -a Opera desktop=
bspc rule -a firefox desktop=
bspc rule -a Spotify desktop=
# bspc rule -a vlc desktop=video
#bspc rule -a Pavucontrol state=floating
#bspc rule -a Qalculate-gtk state=floating
#bspc rule -a Steam desktop=調
#bspc rule -a "Microsoft Teams - Preview" desktop=
bspc rule -a 'zoom ' desktop= state=floating center=on follow=on border=off
bspc rule -a 'zoom' desktop= state=floating center=on follow=on border=off

bspc rule -a plasmashell state=floating border=off sticky=off center=off
bspc rule -a krunner state=floating border=off sticky=off center=off 
#bspc rule -a Ulauncher border=off

bspc config external_rules_command "$HOME/.config/bspwm/rules.sh"

#bspc config focus_follows_pointer true

~/.config/bspwm/lower-plasma.sh
