require("config.colorscheme")
require("config.nvimtree")
require("config.bufferline")
require("config.gitsigns")
require("config.feline")
--require('config.galaxyline')
require("config.floaterm")
require("config.treesitter")
require("config.lsp")
require("config.telescope")

require("ibl").setup()
