require("config.colorscheme")
require("config.nvimtree")
require("config.bufferline")
require("config.gitsigns")
require("config.feline")
require("config.floaterm")
-- require("config.toggleterm")
require("config.treesitter")
require("config.lsp")
require("config.telescope")
require("config.comment")

require("config.statuscol")

require("ibl").setup()
